In [51]:
import pandas as pd
import numpy as np
import os

os.path.abspath("")
print('H')

H

In [52]:
data = pd.read_csv("hashtag_joebiden.csv", encoding='latin1',index_col = False, error_bad_lines=False, lineterminator='\n')
data.head()

,created_at,tweet_id,tweet,likes,retweet_count,source,user_id,user_name,user_screen_name,user_description,...,user_followers_count,user_location,lat,long,city,country,continent,state,state_code,collected_at
0,2020-10-15 00:00:01,1.316529e+18,#Elecciones2020 | En #Florida: #JoeBiden dice ...,0.0,0.0,TweetDeck,3.606665e+08,El Sol Latino News,elsollatinonews,ð Noticias de interÃ©s para latinos de la c...,...,1860.0,"Philadelphia, PA / Miami, FL",25.774270,-80.193660,NaN,United States of America,North America,Florida,FL,2020-10-21 00:00:00
1,2020-10-15 00:00:18,1.316529e+18,#HunterBiden #HunterBidenEmails #JoeBiden #Joe...,0.0,0.0,Twitter for iPad,8.099044e+08,Cheri A. ðºð¸,Biloximeemaw,"Locked and loaded Meemaw. Love God, my family ...",...,6628.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-21 00:00:00.517827283
2,2020-10-15 00:00:20,1.316529e+18,@IslandGirlPRV @BradBeauregardJ @MeidasTouch T...,0.0,0.0,Twitter Web App,3.494182e+09,Flag Waver,Flag_Wavers,NaN,...,1536.0,Golden Valley Arizona,46.304036,-109.171431,NaN,United States of America,North America,Montana,MT,2020-10-21 00:00:01.035654566
3,2020-10-15 00:00:21,1.316529e+18,@chrislongview Watching and setting dvr. Letâ...,0.0,0.0,Twitter for iPhone,8.242596e+17,Michelle Ferg,MichelleFerg4,NaN,...,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-10-21 00:00:01.553481849
4,2020-10-15 00:00:22,1.316529e+18,#censorship #HunterBiden #Biden #BidenEmails #...,1.0,0.0,Twitter Web App,1.032807e+18,the Gold State,theegoldstate,A Silicon Valley #independent #News #Media #St...,...,390.0,"California, USA",36.701463,-118.755997,NaN,United States of America,North America,California,CA,2020-10-21 00:00:02.071309132

In [53]:
data.size

16314606

In [54]:
data.drop(["tweet_id","user_id","source","user_name","user_description","user_followers_count","collected_at"], axis =1,inplace=True)
data.head()

,created_at,tweet,likes,retweet_count,user_screen_name,user_join_date,user_location,lat,long,city,country,continent,state,state_code
0,2020-10-15 00:00:01,#Elecciones2020 | En #Florida: #JoeBiden dice ...,0.0,0.0,elsollatinonews,2011-08-23 15:33:45,"Philadelphia, PA / Miami, FL",25.774270,-80.193660,NaN,United States of America,North America,Florida,FL
1,2020-10-15 00:00:18,#HunterBiden #HunterBidenEmails #JoeBiden #Joe...,0.0,0.0,Biloximeemaw,2012-09-08 01:03:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-10-15 00:00:20,@IslandGirlPRV @BradBeauregardJ @MeidasTouch T...,0.0,0.0,Flag_Wavers,2015-08-30 19:38:21,Golden Valley Arizona,46.304036,-109.171431,NaN,United States of America,North America,Montana,MT
3,2020-10-15 00:00:21,@chrislongview Watching and setting dvr. Letâ...,0.0,0.0,MichelleFerg4,2017-01-25 14:16:17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-10-15 00:00:22,#censorship #HunterBiden #Biden #BidenEmails #...,1.0,0.0,theegoldstate,2018-08-24 01:49:01,"California, USA",36.701463,-118.755997,NaN,United States of America,North America,California,CA

# Checking for null values

In [55]:
data.isnull().sum()

created_at               0
tweet                    0
likes                    0
retweet_count            0
user_screen_name         0
user_join_date           0
user_location       233791
lat                 421593
long                421593
city                590014
country             423107
continent           423089
state               516691
state_code          532277
dtype: int64

In [56]:
df = data.dropna(subset=['user_location','lat'])
df

,created_at,tweet,likes,retweet_count,user_screen_name,user_join_date,user_location,lat,long,city,country,continent,state,state_code
0,2020-10-15 00:00:01,#Elecciones2020 | En #Florida: #JoeBiden dice ...,0.0,0.0,elsollatinonews,2011-08-23 15:33:45,"Philadelphia, PA / Miami, FL",25.774270,-80.193660,NaN,United States of America,North America,Florida,FL
2,2020-10-15 00:00:20,@IslandGirlPRV @BradBeauregardJ @MeidasTouch T...,0.0,0.0,Flag_Wavers,2015-08-30 19:38:21,Golden Valley Arizona,46.304036,-109.171431,NaN,United States of America,North America,Montana,MT
4,2020-10-15 00:00:22,#censorship #HunterBiden #Biden #BidenEmails #...,1.0,0.0,theegoldstate,2018-08-24 01:49:01,"California, USA",36.701463,-118.755997,NaN,United States of America,North America,California,CA
6,2020-10-15 00:00:25,"In 2020, #NYPost is being #censorship #CENSORE...",0.0,0.0,changeillinois,2009-02-02 23:08:28,"Chicago, Illinois",41.875562,-87.624421,Chicago,United States of America,North America,Illinois,IL
11,2020-10-15 00:00:57,"FBI Allegedly Obtained Hunter Biden Computer, ...",0.0,0.0,NewfoundStudio,2018-02-06 04:55:35,"Kentucky, USA",37.572603,-85.155141,NaN,United States of America,North America,Kentucky,KY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
776875,2020-11-08 23:59:15,@elnuevoherald @ngameztorres LOS MEDIOS A LA F...,0.0,0.0,BSC_ROCK1,2020-05-21 12:45:04,Ecuador,-1.339767,-79.366697,NaN,Ecuador,South America,NaN,NaN
776876,2020-11-08 23:59:16,"Mr. #Biden, tear down that wall (with #Mexico)...",1.0,0.0,TimFWelch,2011-09-21 07:13:23,"Auckland, NZ",-36.852095,174.763180,Auckland,New Zealand,Oceania,Auckland,AUK
776879,2020-11-08 23:59:34,@elnuevoherald LOS MEDIOS A LA FUERZA QUIEREN ...,0.0,0.0,BSC_ROCK1,2020-05-21 12:45:04,Ecuador,-1.339767,-79.366697,NaN,Ecuador,South America,NaN,NaN
776881,2020-11-08 23:59:38,Stop laying @CNN !\n#Paris and #London dont gi...,0.0,0.0,flaquet1,2011-10-08 22:42:56,PARIS,48.856697,2.351462,Paris,France,Europe,Ile-de-France,IDF
776883,2020-11-08 23:59:41,L'OTAN va sortir de sa lÃ©thargie et redevenir...,48.0,14.0,CtrlAltDroite,2016-09-30 18:06:56,France,46.603354,1.888334,NaN,France,Europe,NaN,NaN

In [57]:
df.isnull().sum()

created_at               0
tweet                    0
likes                    0
retweet_count            0
user_screen_name         0
user_join_date           0
user_location            0
lat                      0
long                     0
city                168421
country               1514
continent             1496
state                95098
state_code          110684
dtype: int64

# Adding Sentimental analysis

In [7]:
pip install -U textblob

Requirement already up-to-date: textblob in /opt/anaconda3/lib/python3.8/site-packages (0.15.3)
Requirement already satisfied, skipping upgrade: nltk>=3.1 in /opt/anaconda3/lib/python3.8/site-packages (from textblob) (3.5)
Requirement already satisfied, skipping upgrade: click in /opt/anaconda3/lib/python3.8/site-packages (from nltk>=3.1->textblob) (7.1.2)
Requirement already satisfied, skipping upgrade: regex in /opt/anaconda3/lib/python3.8/site-packages (from nltk>=3.1->textblob) (2020.10.15)
Requirement already satisfied, skipping upgrade: joblib in /opt/anaconda3/lib/python3.8/site-packages (from nltk>=3.1->textblob) (0.17.0)
Requirement already satisfied, skipping upgrade: tqdm in /opt/anaconda3/lib/python3.8/site-packages (from nltk>=3.1->textblob) (4.50.2)
Note: you may need to restart the kernel to use updated packages.

In [58]:
#Cleanning up tweet column
df['tidy_tweet'] = df['tweet'].str.replace('[^a-zA-Z#]+',' ')
df.drop(["tweet"], axis =1,inplace=True)
df

<ipython-input-58-d707cd34e5f8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tidy_tweet'] = df['tweet'].str.replace('[^a-zA-Z#]+',' ')
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,created_at,likes,retweet_count,user_screen_name,user_join_date,user_location,lat,long,city,country,continent,state,state_code,tidy_tweet
0,2020-10-15 00:00:01,0.0,0.0,elsollatinonews,2011-08-23 15:33:45,"Philadelphia, PA / Miami, FL",25.774270,-80.193660,NaN,United States of America,North America,Florida,FL,#Elecciones En #Florida #JoeBiden dice que #Do...
2,2020-10-15 00:00:20,0.0,0.0,Flag_Wavers,2015-08-30 19:38:21,Golden Valley Arizona,46.304036,-109.171431,NaN,United States of America,North America,Montana,MT,IslandGirlPRV BradBeauregardJ MeidasTouch Thi...
4,2020-10-15 00:00:22,1.0,0.0,theegoldstate,2018-08-24 01:49:01,"California, USA",36.701463,-118.755997,NaN,United States of America,North America,California,CA,#censorship #HunterBiden #Biden #BidenEmails #...
6,2020-10-15 00:00:25,0.0,0.0,changeillinois,2009-02-02 23:08:28,"Chicago, Illinois",41.875562,-87.624421,Chicago,United States of America,North America,Illinois,IL,In #NYPost is being #censorship #CENSORED by T...
11,2020-10-15 00:00:57,0.0,0.0,NewfoundStudio,2018-02-06 04:55:35,"Kentucky, USA",37.572603,-85.155141,NaN,United States of America,North America,Kentucky,KY,FBI Allegedly Obtained Hunter Biden Computer D...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
776875,2020-11-08 23:59:15,0.0,0.0,BSC_ROCK1,2020-05-21 12:45:04,Ecuador,-1.339767,-79.366697,NaN,Ecuador,South America,NaN,NaN,elnuevoherald ngameztorres LOS MEDIOS A LA FU...
776876,2020-11-08 23:59:16,1.0,0.0,TimFWelch,2011-09-21 07:13:23,"Auckland, NZ",-36.852095,174.763180,Auckland,New Zealand,Oceania,Auckland,AUK,Mr #Biden tear down that wall with #Mexico Wha...
776879,2020-11-08 23:59:34,0.0,0.0,BSC_ROCK1,2020-05-21 12:45:04,Ecuador,-1.339767,-79.366697,NaN,Ecuador,South America,NaN,NaN,elnuevoherald LOS MEDIOS A LA FUERZA QUIEREN ...
776881,2020-11-08 23:59:38,0.0,0.0,flaquet1,2011-10-08 22:42:56,PARIS,48.856697,2.351462,Paris,France,Europe,Ile-de-France,IDF,Stop laying CNN #Paris and #London dont give a...
776883,2020-11-08 23:59:41,48.0,14.0,CtrlAltDroite,2016-09-30 18:06:56,France,46.603354,1.888334,NaN,France,Europe,NaN,NaN,L OTAN va sortir de sa l thargie et redevenir ...

In [59]:
# after the tweet column has been cleaned we used the tidy_tweet to apply the sentimental analyis
import pandas as pd
from textblob import TextBlob

df['sentiment'] = df.tidy_tweet.apply(lambda x: TextBlob(str(x)).sentiment.polarity)
df

<ipython-input-59-899ca2577fd0>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sentiment'] = df.tidy_tweet.apply(lambda x: TextBlob(str(x)).sentiment.polarity)

,created_at,likes,retweet_count,user_screen_name,user_join_date,user_location,lat,long,city,country,continent,state,state_code,tidy_tweet,sentiment
0,2020-10-15 00:00:01,0.0,0.0,elsollatinonews,2011-08-23 15:33:45,"Philadelphia, PA / Miami, FL",25.774270,-80.193660,NaN,United States of America,North America,Florida,FL,#Elecciones En #Florida #JoeBiden dice que #Do...,0.000000
2,2020-10-15 00:00:20,0.0,0.0,Flag_Wavers,2015-08-30 19:38:21,Golden Valley Arizona,46.304036,-109.171431,NaN,United States of America,North America,Montana,MT,IslandGirlPRV BradBeauregardJ MeidasTouch Thi...,0.000000
4,2020-10-15 00:00:22,1.0,0.0,theegoldstate,2018-08-24 01:49:01,"California, USA",36.701463,-118.755997,NaN,United States of America,North America,California,CA,#censorship #HunterBiden #Biden #BidenEmails #...,0.000000
6,2020-10-15 00:00:25,0.0,0.0,changeillinois,2009-02-02 23:08:28,"Chicago, Illinois",41.875562,-87.624421,Chicago,United States of America,North America,Illinois,IL,In #NYPost is being #censorship #CENSORED by T...,-0.148810
11,2020-10-15 00:00:57,0.0,0.0,NewfoundStudio,2018-02-06 04:55:35,"Kentucky, USA",37.572603,-85.155141,NaN,United States of America,North America,Kentucky,KY,FBI Allegedly Obtained Hunter Biden Computer D...,-0.100000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
776875,2020-11-08 23:59:15,0.0,0.0,BSC_ROCK1,2020-05-21 12:45:04,Ecuador,-1.339767,-79.366697,NaN,Ecuador,South America,NaN,NaN,elnuevoherald ngameztorres LOS MEDIOS A LA FU...,0.000000
776876,2020-11-08 23:59:16,1.0,0.0,TimFWelch,2011-09-21 07:13:23,"Auckland, NZ",-36.852095,174.763180,Auckland,New Zealand,Oceania,Auckland,AUK,Mr #Biden tear down that wall with #Mexico Wha...,0.194444
776879,2020-11-08 23:59:34,0.0,0.0,BSC_ROCK1,2020-05-21 12:45:04,Ecuador,-1.339767,-79.366697,NaN,Ecuador,South America,NaN,NaN,elnuevoherald LOS MEDIOS A LA FUERZA QUIEREN ...,0.000000
776881,2020-11-08 23:59:38,0.0,0.0,flaquet1,2011-10-08 22:42:56,PARIS,48.856697,2.351462,Paris,France,Europe,Ile-de-France,IDF,Stop laying CNN #Paris and #London dont give a...,-0.400000
776883,2020-11-08 23:59:41,48.0,14.0,CtrlAltDroite,2016-09-30 18:06:56,France,46.603354,1.888334,NaN,France,Europe,NaN,NaN,L OTAN va sortir de sa l thargie et redevenir ...,0.000000

### Transforming sentimental column

In [61]:
df.drop(["tidy_tweet"], axis =1,inplace=True)
df

KeyError: "['tidy_tweet'] not found in axis"

In [63]:
df['sentiment'].round(2)
df

,created_at,likes,retweet_count,user_screen_name,user_join_date,user_location,lat,long,city,country,continent,state,state_code,sentiment
0,2020-10-15 00:00:01,0.0,0.0,elsollatinonews,2011-08-23 15:33:45,"Philadelphia, PA / Miami, FL",25.774270,-80.193660,NaN,United States of America,North America,Florida,FL,0.000000
2,2020-10-15 00:00:20,0.0,0.0,Flag_Wavers,2015-08-30 19:38:21,Golden Valley Arizona,46.304036,-109.171431,NaN,United States of America,North America,Montana,MT,0.000000
4,2020-10-15 00:00:22,1.0,0.0,theegoldstate,2018-08-24 01:49:01,"California, USA",36.701463,-118.755997,NaN,United States of America,North America,California,CA,0.000000
6,2020-10-15 00:00:25,0.0,0.0,changeillinois,2009-02-02 23:08:28,"Chicago, Illinois",41.875562,-87.624421,Chicago,United States of America,North America,Illinois,IL,-0.148810
11,2020-10-15 00:00:57,0.0,0.0,NewfoundStudio,2018-02-06 04:55:35,"Kentucky, USA",37.572603,-85.155141,NaN,United States of America,North America,Kentucky,KY,-0.100000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
776875,2020-11-08 23:59:15,0.0,0.0,BSC_ROCK1,2020-05-21 12:45:04,Ecuador,-1.339767,-79.366697,NaN,Ecuador,South America,NaN,NaN,0.000000
776876,2020-11-08 23:59:16,1.0,0.0,TimFWelch,2011-09-21 07:13:23,"Auckland, NZ",-36.852095,174.763180,Auckland,New Zealand,Oceania,Auckland,AUK,0.194444
776879,2020-11-08 23:59:34,0.0,0.0,BSC_ROCK1,2020-05-21 12:45:04,Ecuador,-1.339767,-79.366697,NaN,Ecuador,South America,NaN,NaN,0.000000
776881,2020-11-08 23:59:38,0.0,0.0,flaquet1,2011-10-08 22:42:56,PARIS,48.856697,2.351462,Paris,France,Europe,Ile-de-France,IDF,-0.400000
776883,2020-11-08 23:59:41,48.0,14.0,CtrlAltDroite,2016-09-30 18:06:56,France,46.603354,1.888334,NaN,France,Europe,NaN,NaN,0.000000

### Creating Day of the week and time colums

In [64]:
df['created_at'] = pd.to_datetime(df['created_at'])

df['day_of_week'] = df['created_at'].dt.day_name()
df

<ipython-input-64-050e4ef64f9b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['created_at'] = pd.to_datetime(df['created_at'])
<ipython-input-64-050e4ef64f9b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['day_of_week'] = df['created_at'].dt.day_name()

,created_at,likes,retweet_count,user_screen_name,user_join_date,user_location,lat,long,city,country,continent,state,state_code,sentiment,day_of_week
0,2020-10-15 00:00:01,0.0,0.0,elsollatinonews,2011-08-23 15:33:45,"Philadelphia, PA / Miami, FL",25.774270,-80.193660,NaN,United States of America,North America,Florida,FL,0.000000,Thursday
2,2020-10-15 00:00:20,0.0,0.0,Flag_Wavers,2015-08-30 19:38:21,Golden Valley Arizona,46.304036,-109.171431,NaN,United States of America,North America,Montana,MT,0.000000,Thursday
4,2020-10-15 00:00:22,1.0,0.0,theegoldstate,2018-08-24 01:49:01,"California, USA",36.701463,-118.755997,NaN,United States of America,North America,California,CA,0.000000,Thursday
6,2020-10-15 00:00:25,0.0,0.0,changeillinois,2009-02-02 23:08:28,"Chicago, Illinois",41.875562,-87.624421,Chicago,United States of America,North America,Illinois,IL,-0.148810,Thursday
11,2020-10-15 00:00:57,0.0,0.0,NewfoundStudio,2018-02-06 04:55:35,"Kentucky, USA",37.572603,-85.155141,NaN,United States of America,North America,Kentucky,KY,-0.100000,Thursday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
776875,2020-11-08 23:59:15,0.0,0.0,BSC_ROCK1,2020-05-21 12:45:04,Ecuador,-1.339767,-79.366697,NaN,Ecuador,South America,NaN,NaN,0.000000,Sunday
776876,2020-11-08 23:59:16,1.0,0.0,TimFWelch,2011-09-21 07:13:23,"Auckland, NZ",-36.852095,174.763180,Auckland,New Zealand,Oceania,Auckland,AUK,0.194444,Sunday
776879,2020-11-08 23:59:34,0.0,0.0,BSC_ROCK1,2020-05-21 12:45:04,Ecuador,-1.339767,-79.366697,NaN,Ecuador,South America,NaN,NaN,0.000000,Sunday
776881,2020-11-08 23:59:38,0.0,0.0,flaquet1,2011-10-08 22:42:56,PARIS,48.856697,2.351462,Paris,France,Europe,Ile-de-France,IDF,-0.400000,Sunday
776883,2020-11-08 23:59:41,48.0,14.0,CtrlAltDroite,2016-09-30 18:06:56,France,46.603354,1.888334,NaN,France,Europe,NaN,NaN,0.000000,Sunday

In [65]:
import datetime
# extracting time from timestamp
df['Time'] = [datetime.datetime.time(d) for d in df['created_at']] 
df

<ipython-input-65-eb20b04dc590>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Time'] = [datetime.datetime.time(d) for d in df['created_at']]

,created_at,likes,retweet_count,user_screen_name,user_join_date,user_location,lat,long,city,country,continent,state,state_code,sentiment,day_of_week,Time
0,2020-10-15 00:00:01,0.0,0.0,elsollatinonews,2011-08-23 15:33:45,"Philadelphia, PA / Miami, FL",25.774270,-80.193660,NaN,United States of America,North America,Florida,FL,0.000000,Thursday,00:00:01
2,2020-10-15 00:00:20,0.0,0.0,Flag_Wavers,2015-08-30 19:38:21,Golden Valley Arizona,46.304036,-109.171431,NaN,United States of America,North America,Montana,MT,0.000000,Thursday,00:00:20
4,2020-10-15 00:00:22,1.0,0.0,theegoldstate,2018-08-24 01:49:01,"California, USA",36.701463,-118.755997,NaN,United States of America,North America,California,CA,0.000000,Thursday,00:00:22
6,2020-10-15 00:00:25,0.0,0.0,changeillinois,2009-02-02 23:08:28,"Chicago, Illinois",41.875562,-87.624421,Chicago,United States of America,North America,Illinois,IL,-0.148810,Thursday,00:00:25
11,2020-10-15 00:00:57,0.0,0.0,NewfoundStudio,2018-02-06 04:55:35,"Kentucky, USA",37.572603,-85.155141,NaN,United States of America,North America,Kentucky,KY,-0.100000,Thursday,00:00:57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
776875,2020-11-08 23:59:15,0.0,0.0,BSC_ROCK1,2020-05-21 12:45:04,Ecuador,-1.339767,-79.366697,NaN,Ecuador,South America,NaN,NaN,0.000000,Sunday,23:59:15
776876,2020-11-08 23:59:16,1.0,0.0,TimFWelch,2011-09-21 07:13:23,"Auckland, NZ",-36.852095,174.763180,Auckland,New Zealand,Oceania,Auckland,AUK,0.194444,Sunday,23:59:16
776879,2020-11-08 23:59:34,0.0,0.0,BSC_ROCK1,2020-05-21 12:45:04,Ecuador,-1.339767,-79.366697,NaN,Ecuador,South America,NaN,NaN,0.000000,Sunday,23:59:34
776881,2020-11-08 23:59:38,0.0,0.0,flaquet1,2011-10-08 22:42:56,PARIS,48.856697,2.351462,Paris,France,Europe,Ile-de-France,IDF,-0.400000,Sunday,23:59:38
776883,2020-11-08 23:59:41,48.0,14.0,CtrlAltDroite,2016-09-30 18:06:56,France,46.603354,1.888334,NaN,France,Europe,NaN,NaN,0.000000,Sunday,23:59:41

In [66]:
# after extracting time and day_of_week from timestamp I drop created_at
df.drop(["created_at"], axis =1,inplace=True)
df.head(10)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,likes,retweet_count,user_screen_name,user_join_date,user_location,lat,long,city,country,continent,state,state_code,sentiment,day_of_week,Time
0,0.0,0.0,elsollatinonews,2011-08-23 15:33:45,"Philadelphia, PA / Miami, FL",25.774270,-80.193660,NaN,United States of America,North America,Florida,FL,0.00000,Thursday,00:00:01
2,0.0,0.0,Flag_Wavers,2015-08-30 19:38:21,Golden Valley Arizona,46.304036,-109.171431,NaN,United States of America,North America,Montana,MT,0.00000,Thursday,00:00:20
4,1.0,0.0,theegoldstate,2018-08-24 01:49:01,"California, USA",36.701463,-118.755997,NaN,United States of America,North America,California,CA,0.00000,Thursday,00:00:22
6,0.0,0.0,changeillinois,2009-02-02 23:08:28,"Chicago, Illinois",41.875562,-87.624421,Chicago,United States of America,North America,Illinois,IL,-0.14881,Thursday,00:00:25
11,0.0,0.0,NewfoundStudio,2018-02-06 04:55:35,"Kentucky, USA",37.572603,-85.155141,NaN,United States of America,North America,Kentucky,KY,-0.10000,Thursday,00:00:57
17,0.0,0.0,ubaldireports,2010-01-04 04:34:39,"Tampa, Florida",27.947760,-82.458444,Tampa,United States of America,North America,Florida,FL,-1.00000,Thursday,00:01:23
21,1.0,0.0,_dbrown_23,2019-08-24 04:25:30,"Champaign, IL",40.116420,-88.243383,NaN,United States of America,North America,Illinois,IL,0.00000,Thursday,00:01:42
22,1.0,0.0,Joelwhct,2019-06-15 18:24:44,"Hollywood, FL",34.098003,-118.329523,Los Angeles,United States of America,North America,California,CA,0.14000,Thursday,00:01:47
23,0.0,0.0,VandyRick,2012-09-17 04:52:42,United States,39.783730,-100.445882,NaN,United States,North America,NaN,NaN,0.00000,Thursday,00:01:50
25,0.0,0.0,SamKEYS65729181,2020-09-01 16:45:14,"Los Angeles, CA",34.053691,-118.242766,Los Angeles,United States of America,North America,California,CA,0.00000,Thursday,00:01:57

In [67]:
data.to_csv('Biden_Clean_data.csv',index=False)